export const FONT_FAMILIES = [
  { value: "system-ui", label: "System UI" },
  { value: "arial", label: "Arial" },
  { value: "helvetica", label: "Helvetica" },
  { value: "georgia", label: "Georgia" },
  { value: "times", label: "Times New Roman" },
  { value: "courier", label: "Courier New" },
  { value: "verdana", label: "Verdana" },
  { value: "monospace", label: "Monospace" },
];

export const FONT_WEIGHTS = [
  { value: 100, label: "Thin" },
  { value: 200, label: "Extra Light" },
  { value: 300, label: "Light" },
  { value: 400, label: "Regular" },
  { value: 500, label: "Medium" },
  { value: 600, label: "Semi Bold" },
  { value: 700, label: "Bold" },
  { value: 800, label: "Extra Bold" },
  { value: 900, label: "Black" },
] as const;

export const SHADOW_PRESETS = [
  { value: "none", label: "None" },
  { value: "0 1px 2px 0 rgb(0 0 0 / 0.05)", label: "Extra Small" },
  { value: "0 1px 3px 0 rgb(0 0 0 / 0.1)", label: "Small" },
  { value: "0 4px 6px -1px rgb(0 0 0 / 0.1)", label: "Medium" },
  { value: "0 10px 15px -3px rgb(0 0 0 / 0.1)", label: "Large" },
  { value: "0 20px 25px -5px rgb(0 0 0 / 0.1)", label: "Extra Large" },
];

export const BORDER_STYLES = ["solid", "dashed", "dotted", "none"] as const;

export const LINE_HEIGHT_PRESETS = [
  { value: "0.75rem", label: "0.75rem" },
  { value: "1rem", label: "1rem" },
  { value: "1.25rem", label: "1.25rem" },
  { value: "1.5rem", label: "1.5rem" },
  { value: "1.75rem", label: "1.75rem" },
  { value: "2rem", label: "2rem" },
  { value: "2.25rem", label: "2.25rem" },
  { value: "2.5rem", label: "2.5rem" },
];

export const LETTER_SPACING_PRESETS = [
  { value: "-0.05em", label: "-0.05em" },
  { value: "-0.025em", label: "-0.025em" },
  { value: "0", label: "0" },
  { value: "0.025em", label: "0.025em" },
  { value: "0.05em", label: "0.05em" },
  { value: "0.1em", label: "0.1em" },
];

export const SPACING_PRESETS = [
  "0px",
  "1px",
  "2px",
  "4px",
  "6px",
  "8px",
  "10px",
  "12px",
  "14px",
  "16px",
  "20px",
  "24px",
  "28px",
  "32px",
  "36px",
  "40px",
  "44px",
  "48px",
  "56px",
  "64px",
  "80px",
  "96px",
  "112px",
  "128px",
  "144px",
  "160px",
  "176px",
  "192px",
  "208px",
  "224px",
  "240px",
  "256px",
  "288px",
  "320px",
  "384px",
]
  .map((v) => ({ value: v, label: v }))
  .concat({ value: "auto", label: "auto" });

export const SIZE_PRESETS = [
  "0px",
  "1px",
  "2px",
  "4px",
  "6px",
  "8px",
  "10px",
  "12px",
  "14px",
  "16px",
  "20px",
  "24px",
  "28px",
  "32px",
  "36px",
  "40px",
  "44px",
  "48px",
  "56px",
  "64px",
  "80px",
  "96px",
  "112px",
  "128px",
  "144px",
  "160px",
  "176px",
  "192px",
  "208px",
  "224px",
  "240px",
  "256px",
  "288px",
  "320px",
  "384px",
  "1/12",
  "2/12",
  "3/12",
  "4/12",
  "5/12",
  "6/12",
  "7/12",
  "8/12",
  "9/12",
  "10/12",
  "11/12",
  "25%",
  "33%",
  "50%",
  "66%",
  "75%",
  "100%",
  "min-content",
  "max-content",
  "fit-content",
]
  .map((v) => ({ value: v, label: v }))
  .concat({ value: "auto", label: "auto" });

export const BORDER_RADIUS_PRESETS = [
  { value: "0", label: "None" },
  { value: "var(--radius-xs)", label: "Extra Small" },
  { value: "var(--radius-sm)", label: "Small" },
  { value: "var(--radius-md)", label: "Medium" },
  { value: "var(--radius-lg)", label: "Large" },
  { value: "var(--radius-xl)", label: "Extra Large" },
  { value: "var(--radius-2xl)", label: "Double Extra Large" },
  { value: "var(--radius-3xl)", label: "Triple Extra Large" },
  { value: "var(--radius-4xl)", label: "Quadruple Extra Large" },
  { value: "9999px", label: "Full" },
];

export const FONT_SIZE_PRESETS = [
  { value: "xs", label: "xs" },
  { value: "sm", label: "sm" },
  { value: "base", label: "base" },
  { value: "lg", label: "lg" },
  { value: "xl", label: "xl" },
  { value: "2xl", label: "2xl" },
  { value: "3xl", label: "3xl" },
  { value: "4xl", label: "4xl" },
  { value: "5xl", label: "5xl" },
  { value: "6xl", label: "6xl" },
  { value: "7xl", label: "7xl" },
  { value: "8xl", label: "8xl" },
  { value: "9xl", label: "9xl" },
];

export const BORDER_WIDTH_PRESETS = [
  { value: "0", label: "0" },
  { value: "1px", label: "1px" },
  { value: "2px", label: "2px" },
  { value: "4px", label: "4px" },
  { value: "8px", label: "8px" },
];

export const BUTTON_VARIANTS = ["primary", "secondary", "outline", "ghost"] as const;
export const BUTTON_SIZES = ["xs", "sm", "md", "lg", "xl"] as const;
export const TEXT_ALIGN_OPTIONS = ["left", "center", "right", "justify"] as const;
export const TEXT_DECORATION_OPTIONS = [
  "italic",
  "strikethrough",
  "underline",
  "overline",
  "tabular-nums",
] as const;

export const SYSTEM_COLORS = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "border",
  "input",
  "ring",
] as const;

export const TAILWIND_COLORS = [
  { name: "slate-50", className: "bg-slate-50" },
  { name: "slate-100", className: "bg-slate-100" },
  { name: "slate-200", className: "bg-slate-200" },
  { name: "slate-300", className: "bg-slate-300" },
  { name: "slate-400", className: "bg-slate-400" },
  { name: "slate-500", className: "bg-slate-500" },
  { name: "slate-600", className: "bg-slate-600" },
  { name: "slate-700", className: "bg-slate-700" },
  { name: "slate-800", className: "bg-slate-800" },
  { name: "slate-900", className: "bg-slate-900" },
  { name: "slate-950", className: "bg-slate-950" },
  { name: "gray-50", className: "bg-gray-50" },
  { name: "gray-100", className: "bg-gray-100" },
  { name: "gray-200", className: "bg-gray-200" },
  { name: "gray-300", className: "bg-gray-300" },
  { name: "gray-400", className: "bg-gray-400" },
  { name: "gray-500", className: "bg-gray-500" },
  { name: "gray-600", className: "bg-gray-600" },
  { name: "gray-700", className: "bg-gray-700" },
  { name: "gray-800", className: "bg-gray-800" },
  { name: "gray-900", className: "bg-gray-900" },
  { name: "gray-950", className: "bg-gray-950" },
  { name: "red-50", className: "bg-red-50" },
  { name: "red-100", className: "bg-red-100" },
  { name: "red-200", className: "bg-red-200" },
  { name: "red-300", className: "bg-red-300" },
  { name: "red-400", className: "bg-red-400" },
  { name: "red-500", className: "bg-red-500" },
  { name: "red-600", className: "bg-red-600" },
  { name: "red-700", className: "bg-red-700" },
  { name: "red-800", className: "bg-red-800" },
  { name: "red-900", className: "bg-red-900" },
  { name: "red-950", className: "bg-red-950" },
  { name: "orange-50", className: "bg-orange-50" },
  { name: "orange-100", className: "bg-orange-100" },
  { name: "orange-200", className: "bg-orange-200" },
  { name: "orange-300", className: "bg-orange-300" },
  { name: "orange-400", className: "bg-orange-400" },
  { name: "orange-500", className: "bg-orange-500" },
  { name: "orange-600", className: "bg-orange-600" },
  { name: "orange-700", className: "bg-orange-700" },
  { name: "orange-800", className: "bg-orange-800" },
  { name: "orange-900", className: "bg-orange-900" },
  { name: "orange-950", className: "bg-orange-950" },
  { name: "amber-50", className: "bg-amber-50" },
  { name: "amber-100", className: "bg-amber-100" },
  { name: "amber-200", className: "bg-amber-200" },
  { name: "amber-300", className: "bg-amber-300" },
  { name: "amber-400", className: "bg-amber-400" },
  { name: "amber-500", className: "bg-amber-500" },
  { name: "amber-600", className: "bg-amber-600" },
  { name: "amber-700", className: "bg-amber-700" },
  { name: "amber-800", className: "bg-amber-800" },
  { name: "amber-900", className: "bg-amber-900" },
  { name: "amber-950", className: "bg-amber-950" },
  { name: "yellow-50", className: "bg-yellow-50" },
  { name: "yellow-100", className: "bg-yellow-100" },
  { name: "yellow-200", className: "bg-yellow-200" },
  { name: "yellow-300", className: "bg-yellow-300" },
  { name: "yellow-400", className: "bg-yellow-400" },
  { name: "yellow-500", className: "bg-yellow-500" },
  { name: "yellow-600", className: "bg-yellow-600" },
  { name: "yellow-700", className: "bg-yellow-700" },
  { name: "yellow-800", className: "bg-yellow-800" },
  { name: "yellow-900", className: "bg-yellow-900" },
  { name: "yellow-950", className: "bg-yellow-950" },
  { name: "lime-50", className: "bg-lime-50" },
  { name: "lime-100", className: "bg-lime-100" },
  { name: "lime-200", className: "bg-lime-200" },
  { name: "lime-300", className: "bg-lime-300" },
  { name: "lime-400", className: "bg-lime-400" },
  { name: "lime-500", className: "bg-lime-500" },
  { name: "lime-600", className: "bg-lime-600" },
  { name: "lime-700", className: "bg-lime-700" },
  { name: "lime-800", className: "bg-lime-800" },
  { name: "lime-900", className: "bg-lime-900" },
  { name: "lime-950", className: "bg-lime-950" },
  { name: "green-50", className: "bg-green-50" },
  { name: "green-100", className: "bg-green-100" },
  { name: "green-200", className: "bg-green-200" },
  { name: "green-300", className: "bg-green-300" },
  { name: "green-400", className: "bg-green-400" },
  { name: "green-500", className: "bg-green-500" },
  { name: "green-600", className: "bg-green-600" },
  { name: "green-700", className: "bg-green-700" },
  { name: "green-800", className: "bg-green-800" },
  { name: "green-900", className: "bg-green-900" },
  { name: "green-950", className: "bg-green-950" },
  { name: "emerald-50", className: "bg-emerald-50" },
  { name: "emerald-100", className: "bg-emerald-100" },
  { name: "emerald-200", className: "bg-emerald-200" },
  { name: "emerald-300", className: "bg-emerald-300" },
  { name: "emerald-400", className: "bg-emerald-400" },
  { name: "emerald-500", className: "bg-emerald-500" },
  { name: "emerald-600", className: "bg-emerald-600" },
  { name: "emerald-700", className: "bg-emerald-700" },
  { name: "emerald-800", className: "bg-emerald-800" },
  { name: "emerald-900", className: "bg-emerald-900" },
  { name: "emerald-950", className: "bg-emerald-950" },
  { name: "teal-50", className: "bg-teal-50" },
  { name: "teal-100", className: "bg-teal-100" },
  { name: "teal-200", className: "bg-teal-200" },
  { name: "teal-300", className: "bg-teal-300" },
  { name: "teal-400", className: "bg-teal-400" },
  { name: "teal-500", className: "bg-teal-500" },
  { name: "teal-600", className: "bg-teal-600" },
  { name: "teal-700", className: "bg-teal-700" },
  { name: "teal-800", className: "bg-teal-800" },
  { name: "teal-900", className: "bg-teal-900" },
  { name: "teal-950", className: "bg-teal-950" },
  { name: "cyan-50", className: "bg-cyan-50" },
  { name: "cyan-100", className: "bg-cyan-100" },
  { name: "cyan-200", className: "bg-cyan-200" },
  { name: "cyan-300", className: "bg-cyan-300" },
  { name: "cyan-400", className: "bg-cyan-400" },
  { name: "cyan-500", className: "bg-cyan-500" },
  { name: "cyan-600", className: "bg-cyan-600" },
  { name: "cyan-700", className: "bg-cyan-700" },
  { name: "cyan-800", className: "bg-cyan-800" },
  { name: "cyan-900", className: "bg-cyan-900" },
  { name: "cyan-950", className: "bg-cyan-950" },
  { name: "sky-50", className: "bg-sky-50" },
  { name: "sky-100", className: "bg-sky-100" },
  { name: "sky-200", className: "bg-sky-200" },
  { name: "sky-300", className: "bg-sky-300" },
  { name: "sky-400", className: "bg-sky-400" },
  { name: "sky-500", className: "bg-sky-500" },
  { name: "sky-600", className: "bg-sky-600" },
  { name: "sky-700", className: "bg-sky-700" },
  { name: "sky-800", className: "bg-sky-800" },
  { name: "sky-900", className: "bg-sky-900" },
  { name: "sky-950", className: "bg-sky-950" },
  { name: "blue-50", className: "bg-blue-50" },
  { name: "blue-100", className: "bg-blue-100" },
  { name: "blue-200", className: "bg-blue-200" },
  { name: "blue-300", className: "bg-blue-300" },
  { name: "blue-400", className: "bg-blue-400" },
  { name: "blue-500", className: "bg-blue-500" },
  { name: "blue-600", className: "bg-blue-600" },
  { name: "blue-700", className: "bg-blue-700" },
  { name: "blue-800", className: "bg-blue-800" },
  { name: "blue-900", className: "bg-blue-900" },
  { name: "blue-950", className: "bg-blue-950" },
  { name: "indigo-50", className: "bg-indigo-50" },
  { name: "indigo-100", className: "bg-indigo-100" },
  { name: "indigo-200", className: "bg-indigo-200" },
  { name: "indigo-300", className: "bg-indigo-300" },
  { name: "indigo-400", className: "bg-indigo-400" },
  { name: "indigo-500", className: "bg-indigo-500" },
  { name: "indigo-600", className: "bg-indigo-600" },
  { name: "indigo-700", className: "bg-indigo-700" },
  { name: "indigo-800", className: "bg-indigo-800" },
  { name: "indigo-900", className: "bg-indigo-900" },
  { name: "indigo-950", className: "bg-indigo-950" },
  { name: "violet-50", className: "bg-violet-50" },
  { name: "violet-100", className: "bg-violet-100" },
  { name: "violet-200", className: "bg-violet-200" },
  { name: "violet-300", className: "bg-violet-300" },
  { name: "violet-400", className: "bg-violet-400" },
  { name: "violet-500", className: "bg-violet-500" },
  { name: "violet-600", className: "bg-violet-600" },
  { name: "violet-700", className: "bg-violet-700" },
  { name: "violet-800", className: "bg-violet-800" },
  { name: "violet-900", className: "bg-violet-900" },
  { name: "violet-950", className: "bg-violet-950" },
  { name: "purple-50", className: "bg-purple-50" },
  { name: "purple-100", className: "bg-purple-100" },
  { name: "purple-200", className: "bg-purple-200" },
  { name: "purple-300", className: "bg-purple-300" },
  { name: "purple-400", className: "bg-purple-400" },
  { name: "purple-500", className: "bg-purple-500" },
  { name: "purple-600", className: "bg-purple-600" },
  { name: "purple-700", className: "bg-purple-700" },
  { name: "purple-800", className: "bg-purple-800" },
  { name: "purple-900", className: "bg-purple-900" },
  { name: "purple-950", className: "bg-purple-950" },
  { name: "fuchsia-50", className: "bg-fuchsia-50" },
  { name: "fuchsia-100", className: "bg-fuchsia-100" },
  { name: "fuchsia-200", className: "bg-fuchsia-200" },
  { name: "fuchsia-300", className: "bg-fuchsia-300" },
  { name: "fuchsia-400", className: "bg-fuchsia-400" },
  { name: "fuchsia-500", className: "bg-fuchsia-500" },
  { name: "fuchsia-600", className: "bg-fuchsia-600" },
  { name: "fuchsia-700", className: "bg-fuchsia-700" },
  { name: "fuchsia-800", className: "bg-fuchsia-800" },
  { name: "fuchsia-900", className: "bg-fuchsia-900" },
  { name: "fuchsia-950", className: "bg-fuchsia-950" },
  { name: "pink-50", className: "bg-pink-50" },
  { name: "pink-100", className: "bg-pink-100" },
  { name: "pink-200", className: "bg-pink-200" },
  { name: "pink-300", className: "bg-pink-300" },
  { name: "pink-400", className: "bg-pink-400" },
  { name: "pink-500", className: "bg-pink-500" },
  { name: "pink-600", className: "bg-pink-600" },
  { name: "pink-700", className: "bg-pink-700" },
  { name: "pink-800", className: "bg-pink-800" },
  { name: "pink-900", className: "bg-pink-900" },
  { name: "pink-950", className: "bg-pink-950" },
  { name: "rose-50", className: "bg-rose-50" },
  { name: "rose-100", className: "bg-rose-100" },
  { name: "rose-200", className: "bg-rose-200" },
  { name: "rose-300", className: "bg-rose-300" },
  { name: "rose-400", className: "bg-rose-400" },
  { name: "rose-500", className: "bg-rose-500" },
  { name: "rose-600", className: "bg-rose-600" },
  { name: "rose-700", className: "bg-rose-700" },
  { name: "rose-800", className: "bg-rose-800" },
  { name: "rose-900", className: "bg-rose-900" },
  { name: "rose-950", className: "bg-rose-950" },
] as const;

import type {
  TextElementProperties,
  ButtonElementProperties,
  ImageElementProperties,
  DivElementProperties,
} from "./types";

const DEFAULT_SPACING = { top: "0", right: "0", bottom: "0", left: "0" };

export const DEFAULT_TEXT_PROPERTIES: TextElementProperties = {
  width: "auto",
  height: "auto",
  padding: { ...DEFAULT_SPACING },
  margin: { ...DEFAULT_SPACING },
  backgroundColor: "",
  borderRadius: "",
  content: "",
  fontFamily: "",
  fontSize: "",
  fontWeight: 0,
  color: "",
  textAlign: "left",
  textDecoration: "",
  lineHeight: "1.5rem",
  letterSpacing: "0",
  borderWidth: "",
  borderWidthTop: "",
  borderWidthRight: "",
  borderWidthBottom: "",
  borderWidthLeft: "",
  borderStyle: "",
  borderColor: "",
  opacity: 100,
  boxShadow: "",
};

export const DEFAULT_BUTTON_PROPERTIES: ButtonElementProperties = {
  width: "auto",
  height: "auto",
  padding: { ...DEFAULT_SPACING },
  margin: { ...DEFAULT_SPACING },
  backgroundColor: "",
  borderRadius: "",
  text: "",
  variant: "",
  size: "",
  disabled: false,
  content: "",
  fontFamily: "",
  fontSize: "",
  fontWeight: 0,
  color: "",
  textAlign: "left",
  textDecoration: "",
  lineHeight: "1.5rem",
  letterSpacing: "0",
  borderWidth: "",
  borderWidthTop: "",
  borderWidthRight: "",
  borderWidthBottom: "",
  borderWidthLeft: "",
  borderStyle: "",
  borderColor: "",
  opacity: 100,
  boxShadow: "",
};

export const DEFAULT_IMAGE_PROPERTIES: ImageElementProperties = {
  width: "100%",
  height: "auto",
  padding: { ...DEFAULT_SPACING },
  margin: { ...DEFAULT_SPACING },
  backgroundColor: "",
  borderRadius: "",
  src: "",
  alt: "",
  borderWidth: "",
  borderWidthTop: "",
  borderWidthRight: "",
  borderWidthBottom: "",
  borderWidthLeft: "",
  borderStyle: "",
  borderColor: "",
  opacity: 100,
  boxShadow: "",
};

export const DEFAULT_DIV_PROPERTIES: DivElementProperties = {
  width: "auto",
  height: "auto",
  padding: { ...DEFAULT_SPACING },
  margin: { ...DEFAULT_SPACING },
  backgroundColor: "",
  borderRadius: "",
  borderWidth: "",
  borderWidthTop: "",
  borderWidthRight: "",
  borderWidthBottom: "",
  borderWidthLeft: "",
  borderStyle: "",
  borderColor: "",
  opacity: 100,
  boxShadow: "",
};
